name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main # Voer uit bij push naar 'main' branch
  workflow_dispatch: # Handmatig triggerbaar

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Code ophalen uit de repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Maak een outputmap aan
      - name: Prepare files for GitHub Pages
        run: |
          mkdir -p out
          cp -R * out

      # Deploy naar GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./out
